# SPDX-License-Identifier: Apache-2.0
# Keeps pinned Actions/Docker digests fresh with update PRs.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: /
    schedule: { interval: weekly }
