# SPDX-License-Identifier: Apache-2.0
name: OpenSSF Scorecard
on:
  branch_protection_rule: {}
  schedule: [{ cron: "0 2 * * 1" }]
  push: { branches: [main] }
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with: { persist-credentials: false }
      - uses: ossf/scorecard-action@f2ea147fec3c2f0d459703eba7405b5e9bcd8c8f # v2.4.2
        with: { results_format: sarif, results_file: results.sarif, publish_results: true }
      - uses: github/codeql-action/upload-sarif@87ef0dc97def48aa960fbf026a2563ee9dbdb470 # v3
        with: { sarif_file: results.sarif }
